version: '3'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: patternpedia
      POSTGRES_PASSWORD: patternpedia
      POSTGRES_DB: patternpedia
    ports:
      - "5432:5432"
    networks:
      - default
networks:
  default:
    driver: bridge
